# yaml 配置
version: '3'
services:
  web:
    build: .
    ports:
            - "8081:8081"

#  mysql:
#    image: mysql:5.7.27
#    ports:
#    - 3306:3306
#    environment: # 指定用户root的密码
#    - MYSQL_ROOT_PASSWORD=12345
