FROM n2n
#WORKDIR /n2n
#COPY ./installer .
#RUN apt-get update \
#    && apt-get install make \
#    && apt-get install gcc musl-dev g++ zlib-dev \
#    && apt-get install autoconf\
##    && apt-get install libssl-dev \
#    && apt-get install libpng-dev \
#    && make \
#    && make install
#RUN make \
#    && make install
CMD ["supernode", "-l", "7000", "-f"]
