FROM alpine
WORKDIR /n2n
COPY ./n2n_linux .
RUN apt-get install libssl-dev \
    && make \
    && make install
# 没有域名。若云服务器ip变化则需修改下行(-l后)的ip；同时需根据已有的边缘服务器分配(-a后)没有用过的10.0.1.*段ip。(10.0.0.*段给客户端用)
RUN ["/usr/sbin/edge", "-a", "10.0.1.1", "-c","ENSS", "-k","BIT_ENSS", "-l", "124.71.236.106:7000"]